### ISSUE TITLE
LAB 3: String Formatting READY FOR GRADING

### ISSUE THREAD

**Issue by aarandarodriguez-matc** [madisoncollege-it-programs/python-scripting-aarandarodriguez-matc#3]
I made sure to include the code to run it on the command line and to make it executable! Sorry I missed that before. Also, for the brackets, I wasn't sure if it was required to use slicing to get the brackets to the output so I just included them as a string outside of the curly brackets in the print() statement.

I also notice that some of the tags were red when included more than one variable on the print() ( {someVar: ^.1f}, for example}. I tied to fix it but I didn't really understand why they turned red on the editor but still outputted the right statement.

**Comment by cethenmc** [comment]
Hi, Anas.  Great work!  Because this is such excellent work, I don't want to deduct points for at least one line not being accurate with a missing capital letter.  Would you be willing to double-check your work to ensure you output precisely as shown on the assignment?  Since you are in there for that, would you mind removing the single ticks?  I would certainly not take points off as it was a poorly designed question.  The assignment meant the single ticks to signify that it is what is inside of those ticks that should be output.  Again, fantastic and well-organized work.  ~Chris

**Comment by aarandarodriguez-matc** [comment]
Thank you so much, I'll get back in there today and include your suggestions.

**Comment by cethenmc** [comment]
Thank you, Anas!

Chris

[signature_146958654]
Chris Ethen| Information Technology Instructor
Madison College | 1701 Wright Street | Madison, WI  53704
P: 1.608.616.1099 | ***@***.******@***.***>

**Comment by aarandarodriguez-matc** [comment]
Hello,

I have made the corrections. Ty!

**Comment by cethenmc** [comment]
Thanks for making the changes!  It is now graded.  Nice work!
